services:
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: opensigner
      MYSQL_DATABASE: opensigner_poc
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-popensigner"]
      interval: 5s
      timeout: 5s
      retries: 20
